import type { Checkin, Message, Sighting, PersonalNote, AnonymousTip, AnyRecord } from '@/store/types';

// ===== CHECKINS =====
export const checkins: Checkin[] = [
  {
    id: 'chk-1',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:05:00',
    personName: 'Podo',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Etkinlik başlangıcında giriş yaptı. Mor ceketli ve oldukça neşeliydi.',
    note: 'Etkinlik başlangıcında giriş yaptı. Mor ceketli ve oldukça neşeliydi.',
  },
  {
    id: 'chk-2',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:07:00',
    personName: 'Kağan',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Podo ile özel olarak sonra konuşmak istediğini söyledi.',
    note: 'Podo ile özel olarak sonra konuşmak istediğini söyledi.',
  },
  {
    id: 'chk-3',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:08:00',
    personName: 'Can',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Podo ile selamlaşıp fotoğraf çekildi.',
    note: 'Podo ile selamlaşıp fotoğraf çekildi.',
  },
  {
    id: 'chk-4',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:10:00',
    personName: 'Cem',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Teknik ekip alanına yakın giriş yaptı.',
    note: 'Teknik ekip alanına yakın giriş yaptı.',
  },
  {
    id: 'chk-5',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:11:00',
    personName: 'Hami',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: "Podo'nun gece planını merak ediyordu.",
    note: "Podo'nun gece planını merak ediyordu.",
  },
  {
    id: 'chk-6',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:12:00',
    personName: 'Eray',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: "Podo'nun akşam kimlerle gezeceğini soruyordu.",
    note: "Podo'nun akşam kimlerle gezeceğini soruyordu.",
  },
  {
    id: 'chk-7',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:13:00',
    personName: 'Gülşah',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Podo ile kısa sohbet etti.',
    note: 'Podo ile kısa sohbet etti.',
  },
  {
    id: 'chk-8',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:14:00',
    personName: 'Aslı',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Gece için minik bir sürpriz hazırladığını söyledi.',
    note: 'Gece için minik bir sürpriz hazırladığını söyledi.',
  },
  {
    id: 'chk-9',
    sourceType: 'checkin',
    timestamp: '2026-04-18T19:16:00',
    personName: 'Fatih',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Yanında gizemli küçük bir çanta vardı.',
    note: 'Yanında gizemli küçük bir çanta vardı.',
  },
];

// ===== MESSAGES =====
export const messages: Message[] = [
  {
    id: 'msg-1',
    sourceType: 'message',
    timestamp: '2026-04-18T20:02:00',
    personName: 'Podo',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Buradaki kalabalık iyiymiş. Sonra Tunalı tarafına geçen olur mu?',
    senderName: 'Podo',
    recipientName: 'Aslı',
    text: 'Buradaki kalabalık iyiymiş. Sonra Tunalı tarafına geçen olur mu?',
    urgency: 'low',
    relatedPersons: ['Podo', 'Aslı'],
  },
  {
    id: 'msg-2',
    sourceType: 'message',
    timestamp: '2026-04-18T20:04:00',
    personName: 'Aslı',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: 'Olur bence. Ben birazdan çıkabilirim.',
    senderName: 'Aslı',
    recipientName: 'Podo',
    text: 'Olur bence. Ben birazdan çıkabilirim.',
    urgency: 'low',
    relatedPersons: ['Aslı', 'Podo'],
  },
  {
    id: 'msg-3',
    sourceType: 'message',
    timestamp: '2026-04-18T20:18:00',
    personName: 'Podo',
    location: 'Tunalı Hilmi Caddesi',
    coordinates: '39.90584,32.86089',
    content: 'Sen yine bir şeyler kuruyorsun galiba 😄 Neredesin?',
    senderName: 'Podo',
    recipientName: 'Cem',
    text: 'Sen yine bir şeyler kuruyorsun galiba 😄 Neredesin?',
    urgency: 'low',
    relatedPersons: ['Podo', 'Cem'],
  },
  {
    id: 'msg-4',
    sourceType: 'message',
    timestamp: '2026-04-18T20:19:00',
    personName: 'Cem',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: "Ben hâlâ teknik tarafa bakıyorum, Tunalı'da değilim.",
    senderName: 'Cem',
    recipientName: 'Podo',
    text: "Ben hâlâ teknik tarafa bakıyorum, Tunalı'da değilim.",
    urgency: 'medium',
    relatedPersons: ['Cem', 'Podo'],
  },
  {
    id: 'msg-5',
    sourceType: 'message',
    timestamp: '2026-04-18T20:31:00',
    personName: 'Podo',
    location: 'Kuğulu Park',
    coordinates: '39.90194,32.86028',
    content: 'O çantada ne var ya, herkes seni aşırı gizemli buluyor.',
    senderName: 'Podo',
    recipientName: 'Fatih',
    text: 'O çantada ne var ya, herkes seni aşırı gizemli buluyor.',
    urgency: 'low',
    relatedPersons: ['Podo', 'Fatih'],
  },
  {
    id: 'msg-6',
    sourceType: 'message',
    timestamp: '2026-04-18T20:32:00',
    personName: 'Fatih',
    location: 'Kuğulu Park',
    coordinates: '39.90194,32.86028',
    content: 'Sürpriz bir şey, yanlış anlaşılacak diye göstermiyorum 😅',
    senderName: 'Fatih',
    recipientName: 'Podo',
    text: 'Sürpriz bir şey, yanlış anlaşılacak diye göstermiyorum 😅',
    urgency: 'medium',
    relatedPersons: ['Fatih', 'Podo'],
  },
  {
    id: 'msg-7',
    sourceType: 'message',
    timestamp: '2026-04-18T20:44:00',
    personName: 'Kağan',
    location: 'Seğmenler Parkı',
    coordinates: '39.89333,32.86353',
    content: 'Sana gece sonu için çok iyi bir sürpriz göstereceğim. Kalabalıktan biraz uzaklaşalım mı?',
    senderName: 'Kağan',
    recipientName: 'Podo',
    text: 'Sana gece sonu için çok iyi bir sürpriz göstereceğim. Kalabalıktan biraz uzaklaşalım mı?',
    urgency: 'high',
    relatedPersons: ['Kağan', 'Podo'],
  },
  {
    id: 'msg-8',
    sourceType: 'message',
    timestamp: '2026-04-18T20:45:00',
    personName: 'Podo',
    location: 'Seğmenler Parkı',
    coordinates: '39.89333,32.86353',
    content: 'Yine mi gizemli konuşuyorsun? Tamam ama çok uzaklaşmayalım.',
    senderName: 'Podo',
    recipientName: 'Kağan',
    text: 'Yine mi gizemli konuşuyorsun? Tamam ama çok uzaklaşmayalım.',
    urgency: 'medium',
    relatedPersons: ['Podo', 'Kağan'],
  },
  {
    id: 'msg-9',
    sourceType: 'message',
    timestamp: '2026-04-18T20:53:00',
    personName: 'Gülşah',
    location: 'Atakule',
    coordinates: '39.88645,32.85558',
    content: "Podo'yu az önce Kağan'la birlikte aşağı doğru yürürken gördüm.",
    senderName: 'Gülşah',
    recipientName: 'Aslı',
    text: "Podo'yu az önce Kağan'la birlikte aşağı doğru yürürken gördüm.",
    urgency: 'high',
    relatedPersons: ['Gülşah', 'Aslı', 'Podo', 'Kağan'],
  },
];

// ===== SIGHTINGS =====
export const sightings: Sighting[] = [
  {
    id: 'sig-1',
    sourceType: 'sighting',
    timestamp: '2026-04-18T19:30:00',
    personName: 'Podo',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: "Podo sahnede konuşma yapıyordu, çevresinde kalabalık vardı.",
    witnessName: 'Can',
    description: "Podo sahnede konuşma yapıyordu, çevresinde kalabalık vardı.",
    relatedPersons: ['Podo', 'Can'],
  },
  {
    id: 'sig-2',
    sourceType: 'sighting',
    timestamp: '2026-04-18T20:10:00',
    personName: 'Podo',
    location: 'Tunalı Hilmi Caddesi',
    coordinates: '39.90584,32.86089',
    content: "Podo CerModern'den ayrılırken görüldü, Tunalı yönüne yürüyordu.",
    witnessName: 'Eray',
    description: "Podo CerModern'den ayrılırken görüldü, Tunalı yönüne yürüyordu.",
    relatedPersons: ['Podo', 'Eray'],
  },
  {
    id: 'sig-3',
    sourceType: 'sighting',
    timestamp: '2026-04-18T20:35:00',
    personName: 'Podo',
    location: 'Kuğulu Park',
    coordinates: '39.90194,32.86028',
    content: "Podo, Kuğulu Park'ta Fatih ile oturuyordu. İkisi gülüyormuş.",
    witnessName: 'Hami',
    description: "Podo, Kuğulu Park'ta Fatih ile oturuyordu. İkisi gülüyormuş.",
    relatedPersons: ['Podo', 'Fatih', 'Hami'],
  },
  {
    id: 'sig-4',
    sourceType: 'sighting',
    timestamp: '2026-04-18T20:50:00',
    personName: 'Podo',
    location: 'Seğmenler Parkı',
    coordinates: '39.89333,32.86353',
    content: "Podo ile Kağan, Seğmenler Parkı'ndan güneye doğru yürüyorlardı.",
    witnessName: 'Gülşah',
    description: "Podo ile Kağan, Seğmenler Parkı'ndan güneye doğru yürüyorlardı.",
    relatedPersons: ['Podo', 'Kağan', 'Gülşah'],
  },
  {
    id: 'sig-5',
    sourceType: 'sighting',
    timestamp: '2026-04-18T21:05:00',
    personName: 'Podo',
    location: 'Atakule',
    coordinates: '39.88645,32.85558',
    content: "Podo Atakule yakınında son kez görüldü, yalnızdı ve aceleymiş gibi görünüyordu.",
    witnessName: 'Aslı',
    description: "Podo Atakule yakınında son kez görüldü, yalnızdı ve aceleymiş gibi görünüyordu.",
    relatedPersons: ['Podo', 'Aslı'],
  },
];

// ===== PERSONAL NOTES =====
export const personalNotes: PersonalNote[] = [
  {
    id: 'note-1',
    sourceType: 'note',
    timestamp: '2026-04-18T19:20:00',
    personName: 'Can',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: "Podo bu gece çok enerjik görünüyor. Herkesle konuşmaya çalışıyor.",
    author: 'Can',
    text: "Podo bu gece çok enerjik görünüyor. Herkesle konuşmaya çalışıyor.",
  },
  {
    id: 'note-2',
    sourceType: 'note',
    timestamp: '2026-04-18T19:45:00',
    personName: 'Cem',
    location: 'CerModern',
    coordinates: '39.93159,32.84967',
    content: "Kağan, Podo'yla özel konuşmak istediğini söyledi. Biraz garip geldi.",
    author: 'Cem',
    text: "Kağan, Podo'yla özel konuşmak istediğini söyledi. Biraz garip geldi.",
  },
  {
    id: 'note-3',
    sourceType: 'note',
    timestamp: '2026-04-18T20:25:00',
    personName: 'Aslı',
    location: 'Tunalı Hilmi Caddesi',
    coordinates: '39.90584,32.86089',
    content: "Fatih'in çantası hakkında herkes konuşuyor. Ama Fatih iyi biri, abartmayalım.",
    author: 'Aslı',
    text: "Fatih'in çantası hakkında herkes konuşuyor. Ama Fatih iyi biri, abartmayalım.",
  },
  {
    id: 'note-4',
    sourceType: 'note',
    timestamp: '2026-04-18T21:00:00',
    personName: 'Hami',
    location: 'Seğmenler Parkı',
    coordinates: '39.89333,32.86353',
    content: "Podo'yu Kağan'la son gören kişi Gülşah. Sonrasında kimse görmemiş.",
    author: 'Hami',
    text: "Podo'yu Kağan'la son gören kişi Gülşah. Sonrasında kimse görmemiş.",
  },
];

// ===== ANONYMOUS TIPS =====
export const anonymousTips: AnonymousTip[] = [
  {
    id: 'tip-1',
    sourceType: 'tip',
    timestamp: '2026-04-18T21:15:00',
    personName: undefined,
    location: 'Seğmenler Parkı',
    coordinates: '39.89333,32.86353',
    content: "Kağan'ın Podo'yu kalabalıktan uzaklaştırmak istediğini duydum. Sonra ikisi birlikte kayboldu.",
    text: "Kağan'ın Podo'yu kalabalıktan uzaklaştırmak istediğini duydum. Sonra ikisi birlikte kayboldu.",
    reliability: 'high',
    relatedPersons: ['Kağan', 'Podo'],
  },
  {
    id: 'tip-2',
    sourceType: 'tip',
    timestamp: '2026-04-18T21:20:00',
    personName: undefined,
    location: 'Atakule',
    coordinates: '39.88645,32.85558',
    content: "Fatih'in çantasında Podo için hazırlanmış bir hediye vardı. Bu bilgiyi bilen yok.",
    text: "Fatih'in çantasında Podo için hazırlanmış bir hediye vardı. Bu bilgiyi bilen yok.",
    reliability: 'medium',
    relatedPersons: ['Fatih', 'Podo'],
  },
  {
    id: 'tip-3',
    sourceType: 'tip',
    timestamp: '2026-04-18T21:30:00',
    personName: undefined,
    location: 'Ankara',
    coordinates: '39.9334,32.8597',
    content: "Eray akşam boyunca Podo'nun nereye gittiğini takip ediyordu. Çok soru soruyordu.",
    text: "Eray akşam boyunca Podo'nun nereye gittiğini takip ediyordu. Çok soru soruyordu.",
    reliability: 'medium',
    relatedPersons: ['Eray', 'Podo'],
  },
  {
    id: 'tip-4',
    sourceType: 'tip',
    timestamp: '2026-04-18T21:45:00',
    personName: undefined,
    location: 'Atakule',
    coordinates: '39.88645,32.85558',
    content: "Podo son kez Atakule'nin arkasında görüldü. Yanında kimse yoktu.",
    text: "Podo son kez Atakule'nin arkasında görüldü. Yanında kimse yoktu.",
    reliability: 'high',
    relatedPersons: ['Podo'],
  },
];

// ===== ALL RECORDS MERGED =====
export const allRecords: AnyRecord[] = [
  ...checkins,
  ...messages,
  ...sightings,
  ...personalNotes,
  ...anonymousTips,
].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());
